/**
 * build_pdf.js — NeetCode 150 PDF Book Generator
 * Usage: node build_pdf.js
 */

const puppeteer = require('puppeteer');
const { marked }  = require('marked');
const fs   = require('fs');
const path = require('path');
const https = require('https');
const http  = require('http');

const BACKUP       = path.join(__dirname, 'NeetCode_150_Backup');
const META_FILE    = path.join(BACKUP, 'metadata.json');
const TOPICS_FILE  = path.join(__dirname, 'topicsAndProblems.md');
const OUT_PDF      = path.join(__dirname, 'NeetCode_150_Book.pdf');

// ── Image download + base64 embed ────────────────────────────────────────────
function fetchImage(url) {
  return new Promise((resolve) => {
    const lib = url.startsWith('https') ? https : http;
    lib.get(url, (res) => {
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => {
        const buf = Buffer.concat(chunks);
        const ct  = res.headers['content-type'] || 'image/png';
        resolve(`data:${ct};base64,${buf.toString('base64')}`);
      });
    }).on('error', () => resolve(url));
  });
}

async function embedImages(mdText) {
  const imgRe = /!\[([^\]]*)\]\((https?:\/\/[^)]+)\)/g;
  const matches = [...mdText.matchAll(imgRe)];
  for (const m of matches) {
    const dataUri = await fetchImage(m[2]);
    mdText = mdText.replace(m[0], `![${m[1]}](${dataUri})`);
  }
  return mdText;
}

// ── Markdown helpers ─────────────────────────────────────────────────────────
function normalizeCodeFences(md) {
  return md.replace(/^```\w+/gm, '```');
}

function expandListIndents(md) {
  return md.split('\n').map(line => {
    const m = line.match(/^( +)([-*+]|\d+\.)\s/);
    if (m) {
      const newSpaces = Math.ceil(m[1].length / 2) * 4;
      return ' '.repeat(newSpaces) + line.trimStart();
    }
    return line;
  }).join('\n');
}

function mdToHtml(md) {
  md = normalizeCodeFences(md);
  md = expandListIndents(md);
  return marked.parse(md);
}

// ── Parse topicsAndProblems.md ───────────────────────────────────────────────
function parseSections(meta) {
  const nameToNum = {};
  for (const p of meta.problems) {
    nameToNum[p.name.toLowerCase().trim()] = p.num;
  }

  const sections = [];
  let curSection = null, curProblems = [];

  for (const rawLine of fs.readFileSync(TOPICS_FILE, 'utf8').split('\n')) {
    const line = rawLine.trim();
    if (line.startsWith('## ')) {
      if (curSection) sections.push({ name: curSection, nums: curProblems });
      curSection  = line.replace(/^##\s+\d+\.\s*/, '').trim();
      curProblems = [];
    } else if (/^\d+\.\s+/.test(line)) {
      const probName = line.replace(/^\d+\.\s+/, '').trim();
      const key = probName.toLowerCase().trim();
      let num = nameToNum[key];
      if (!num) {
        for (const [k, v] of Object.entries(nameToNum)) {
          if (k.includes(key) || key.includes(k)) { num = v; break; }
        }
      }
      if (num) curProblems.push(num);
    }
  }
  if (curSection) sections.push({ name: curSection, nums: curProblems });
  return sections;
}

// ── HTML page builders ───────────────────────────────────────────────────────
function coverPage() {
  return `
  <div class="page cover-page">
    <h1>NeetCode 150</h1>
    <h2>Questions &amp; Solutions</h2>
    <p class="subtitle">Java Solutions &nbsp;·&nbsp; All 150 Problems</p>
  </div>`;
}

function creditsPage() {
  return `
  <div class="page credits-page">
    <h2>Credits &amp; Disclaimer</h2>
    <p><strong>Source:</strong> All problems and solutions are sourced from<br>
    <a href="https://neetcode.io/practice/neetcode150">https://neetcode.io/practice/neetcode150</a></p>
    <p><strong>Author:</strong> NeetCode</p>
    <br>
    <h3>Disclaimer</h3>
    <p>This document was generated programmatically using a custom web scraper
    built with Python and Playwright, with assistance from AI tools (Amazon Q Developer).
    It is intended solely for personal offline study and reference.</p>
    <p>All content — problem statements, solutions, explanations, and code —
    belongs to NeetCode. No content has been modified, summarized, or generated by AI.
    The scraper only collected and formatted existing content.</p>
    <p>This PDF is not for redistribution or commercial use.</p>
  </div>`;
}

function sectionPage(name, nums, numMap) {
  const items = nums
    .filter(n => numMap[n])
    .map(n => `<li>${numMap[n].name}</li>`)
    .join('\n');
  return `
  <div class="page section-page">
    <h1>${name}</h1>
    <ol>${items}</ol>
  </div>`;
}

// ── CSS ───────────────────────────────────────────────────────────────────────
const CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    font-family: Palatino, "Palatino Linotype", "Book Antiqua", Georgia, serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #111;
    background: white;
  }

  .page { page-break-after: always; padding: 0; }

  .cover-page {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    text-align: center;
  }
  .cover-page h1 { font-size: 26pt; border-bottom: 2px solid #111; padding-bottom: 12px; margin-bottom: 16px; }
  .cover-page h2 { font-size: 15pt; font-weight: normal; color: #444; margin-bottom: 24px; border: none; }
  .cover-page .subtitle { font-size: 10pt; color: #777; }

  .credits-page { padding: 4cm 2cm; }
  .credits-page h2 { font-size: 14pt; margin-bottom: 1em; border-bottom: 1px solid #ccc; padding-bottom: 6px; }
  .credits-page h3 { font-size: 12pt; margin: 1.2em 0 0.5em; }
  .credits-page p  { margin-bottom: 0.8em; line-height: 1.7; }
  .credits-page a  { color: #111; }

  .section-page {
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 3cm 2cm;
    height: 100vh;
  }
  .section-page h1 { font-size: 22pt; border-bottom: 2px solid #111; padding-bottom: 10px; margin-bottom: 1.2em; }
  .section-page ol { font-size: 11pt; line-height: 1.8; margin-left: 1.5em; }

  .problem-block  { page-break-after: always; }
  .hint-block     { page-break-after: always; }
  .solution-block { page-break-after: always; }

  h1 { font-size: 17.5pt; margin: 0.5em 0 0.4em; page-break-after: avoid; border-bottom: 1.5px solid #333; padding-bottom: 4px; }
  h2 { font-size: 14pt;   margin: 1em 0 0.3em;   page-break-after: avoid; }
  h3 { font-size: 12pt;   margin: 0.9em 0 0.25em; page-break-after: avoid; }
  h4 { font-size: 11pt;   margin: 0.8em 0 0.2em;  page-break-after: avoid; font-style: italic; }
  h5 { font-size: 10.5pt; margin: 0.7em 0 0.2em;  page-break-after: avoid; }

  p  { margin: 0.3em 0 0.55em; orphans: 3; widows: 3; }
  ul, ol { margin: 0.3em 0 0.5em 1.4em; }
  li { margin: 0.15em 0; orphans: 3; widows: 3; }
  li > ul, li > ol { margin-top: 0.15em; margin-bottom: 0.15em; margin-left: 1.4em; }

  pre {
    font-family: Consolas, "DejaVu Sans Mono", "Courier New", monospace;
    font-size: 10pt;
    font-weight: normal;
    line-height: 1.5;
    background: none;
    border: none;
    padding: 0;
    margin: 0.8em 0 0.8em 1.5em;
    white-space: pre;
    page-break-inside: auto;
  }

  code {
    font-family: Consolas, "DejaVu Sans Mono", "Courier New", monospace;
    font-size: 10pt;
    font-weight: normal;
    background: none;
    padding: 0;
  }

  p > code, li > code { font-style: italic; }

  pre code {
    font-style: normal;
    font-size: inherit;
    background: none;
    padding: 0;
  }

  img { max-width: 100%; height: auto; display: block; margin: 0.7em auto; }

  blockquote {
    border-left: 3px solid #aaa;
    margin: 0.5em 0 0.5em 1em;
    padding-left: 0.8em;
    color: #555;
    font-style: italic;
  }

  table { border-collapse: collapse; width: 100%; margin: 0.6em 0; font-size: 9.5pt; }
  th, td { border: 1px solid #ccc; padding: 4px 8px; text-align: left; }
  th { background: #eee; font-weight: bold; }

  strong { font-weight: bold; }
  em     { font-style: italic; }
  a      { color: #111; text-decoration: none; }
`;

// ── Main ─────────────────────────────────────────────────────────────────────
(async () => {
  const meta   = JSON.parse(fs.readFileSync(META_FILE, 'utf8'));
  const numMap = {};
  for (const p of meta.problems) numMap[p.num] = p;
  const sections = parseSections(meta);

  const parts = [];
  parts.push(coverPage());
  parts.push(creditsPage());

  for (let secIdx = 0; secIdx < sections.length; secIdx++) {
    const { name, nums } = sections[secIdx];
    parts.push(sectionPage(name, nums, numMap));

    for (let qIdx = 0; qIdx < nums.length; qIdx++) {
      const n = nums[qIdx];
      if (!numMap[n]) continue;
      const folder = path.join(BACKUP, numMap[n].folder);

      // Problem Statement
      const psFile = path.join(folder, 'Problem_Statement.md');
      if (fs.existsSync(psFile)) {
        let md = fs.readFileSync(psFile, 'utf8');
        md = await embedImages(md);
        const html = mdToHtml(md);
        parts.push(`<div class="problem-block">${html}</div>`);
      }

      // Hint Page (optional)
      const hintFile = path.join(folder, 'Hint_page.md');
      if (fs.existsSync(hintFile)) {
        let md = fs.readFileSync(hintFile, 'utf8');
        md = await embedImages(md);
        const html = mdToHtml(md);
        parts.push(`<div class="hint-block">${html}</div>`);
      }

      // Solution
      let solFile = path.join(folder, 'Solution.md');
      if (!fs.existsSync(solFile)) solFile = path.join(folder, 'Solution.txt');
      if (fs.existsSync(solFile)) {
        let md = fs.readFileSync(solFile, 'utf8');
        md = await embedImages(md);
        const html = mdToHtml(md);
        parts.push(`<div class="solution-block">${html}</div>`);
      }
    }
  }

  const fullHtml = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>${CSS}</style>
</head>
<body>
${parts.join('\n')}
</body>
</html>`;

  console.log('Launching browser...');
  const browser = await puppeteer.launch({ headless: true });
  const page    = await browser.newPage();

  await page.setContent(fullHtml, { waitUntil: 'networkidle0' });

  console.log('Rendering PDF...');
  await page.pdf({
    path: OUT_PDF,
    format: 'A4',
    printBackground: true,
    margin: { top: '1.6cm', bottom: '1.6cm', left: '2cm', right: '2cm' },
    displayHeaderFooter: true,
    headerTemplate: '<span></span>',
    footerTemplate: `<div style="width:100%;text-align:center;font-size:9px;font-family:Palatino,'Palatino Linotype',Georgia,serif;color:#333;padding:0 2cm;">
      <span class="pageNumber"></span>
    </div>`,
  });

  await browser.close();
  console.log('✅ PDF saved:', OUT_PDF);
})();
